export const REEL_SCHEMAS = {
  reel_issue: {
    sheetName: 'ALL IN ONE - REEL ISSUE',
    headers: [
      'S NO.',
      'JOB NO.',
      'QR Scan',
      'G. E. No.',
      'Date',
      'MRR Number',
      'Dt. of Receipt',
      'Sup Doc No.',
      'Truck Number',
      'Invoice Ttl Weight (Kgs)',
      'Actual MRR Ttl Weight (Kgs)',
      'PO NO.',
      'PO DATE',
      'SUPPLIER',
      'Our Reel Number',
      'Supplier Reel No.',
      'REEL DETAILS',
      'ERP Code',
      'Size',
      'GSM',
      'BF',
      'Weight',
      'Rate',
      'CORRUGATION',
      'A',
      'B',
      'C',
      'D',
      'E',
      'HIGHEST',
      'ISSUE DATE',
      'Issue Id',
      'Issue Item Id',
      'VALUE'
    ]
  },
  reel_return: {
    sheetName: 'ALL IN ONE - REEL RETURN',
    headers: [
      'S NO.',
      'JOB',
      'QR Scan',
      'Supplier Reel No.',
      'ERP Code',
      'Size',
      'GSM',
      'BF',
      'Weight',
      'Rate',
      'RETURN DATE',
      'CORRUGATION',
      'Return Item Id',
      'Reel Return Id',
      'Return PDF',
      'RETURN MSG',
      'RETURN EMAIL',
      'VALUE',
      'JOB TRANSFER',
      'Telegram MSG'
    ]
  },
  sheet_plant_pending: {
    sheetName: 'ALL IN ONE - PENDING SHEET PLANT',
    headers: [
      'S NO.',
      'DATE',
      'JOB No.',
      'ERP',
      'ITEM',
      'PLAN QUANTITY',
      'REQUIRED REEL (Kgs)',
      'ACTUAL PAPER USED (Kgs)',
      'PART PRODUCTION (Boxes)',
      'FULL CORRUGATION QNT. (Boxes)',
      'PROD. AT SHEET PLANT (Boxes)',
      'WARPAGE (Boxes) ',
      'WARPAGE (Kgs)',
      'DELAMINATION (Boxes)',
      'DELAMINATION (Kgs))',
      'MISALIGNMENT (Boxes)',
      'MISALIGNMENT (Kgs)',
      '2PLY & PAPER (Kgs)',
      'DECKEL WASTAGE',
      'SHEER CUTTER (Boxes)',
      'SHEER CUTTER (Kgs)',
      'NO HISAB',
      'PENDING ID',
      'TOTAL C WASTAGE',
      'PERCENTAGE',
      'SELECT REELS TO TRANSFER',
      'SELECT JOB NO TO TRANSFER',
      'ROW ADDED IN REEL ISSUE/RETURN',
      'Average Notional wheight per reel',
      'RATE',
      'BASIC_Value',
      'Timestamp'
    ]
  },
  printing_pending: {
    sheetName: 'ALL IN ONE - PENDING FOR PRINTING',
    headers: [
      'S NO.',
      'DATE',
      'JOB No.',
      'ERP',
      'ITEM',
      'PLAN QUANTITY',
      'REQUIRED REEL',
      'ACTUAL PAPER USED',
      'PROD. AT SHEET PLANT',
      'WARPAGE',
      'DELAMINATION',
      'MISALIGNMENT (Kgs)',
      '2PLY & PAPER Kg',
      'DECKEL WASTAGE',
      'SHEER CUTTER',
      'PART PRINTING',
      'PROD. AT PRINTING',
      'FG',
      'SLOTTING',
      'DELAMINATION',
      'MISALIGNMENT',
      'DRY SHEETS',
      'WARP',
      'MISPRINTING',
      'JOB SETTING',
      'HELPER',
      'C WASTAGE',
      'TOTAL WASTAGE %',
      'Timestamp',
      'PO PDF',
      'P WASTAGE'
    ]
  },
  closer_pending: {
    sheetName: 'ALL IN ONE - PENDING FOR CLOSER',
    headers: [
      'S NO.',
      'DATE',
      'JOB No.',
      'ERP',
      'ITEM',
      'PLAN QUANTITY',
      'REQUIRED REEL',
      'ACTUAL PAPER USED',
      'PROD. AT SHEET PLANT',
      'WARPAGE',
      'DELAMINATION',
      'MISALIGNMENT (Kgs)',
      '2PLY & PAPER Kg',
      'DECKEL WASTAGE',
      'SHEER CUTTER',
      'PART PRINTING',
      'PROD. AT PRINTING',
      'FG',
      'SLOTTING',
      'DELAMINATION',
      'MISALIGNMENT',
      'DRY SHEETS',
      'WARP',
      'MISPRINTING',
      'JOB SETTING',
      'HELPER',
      'REASON'
    ]
  }
};

