CREATE TABLE IF NOT EXISTS app_users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  login_id VARCHAR(120) NOT NULL,
  user_email VARCHAR(190) DEFAULT NULL,
  mobile_no VARCHAR(30) DEFAULT NULL,
  display_name VARCHAR(190) DEFAULT NULL,
  role VARCHAR(80) DEFAULT NULL,
  menu_access LONGTEXT DEFAULT NULL,
  password_hash VARCHAR(255) DEFAULT NULL,
  password_plain VARCHAR(190) DEFAULT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_firm_login (firm_id, login_id),
  KEY idx_users_email (user_email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO app_users
  (firm_id, login_id, user_email, display_name, role, menu_access, password_hash, password_plain, active)
VALUES
  ('lnki', 'system', 'system@lngrp.in', 'System', 'admin', NULL, NULL, 'abcd', 1)
ON DUPLICATE KEY UPDATE
  user_email = VALUES(user_email),
  display_name = VALUES(display_name),
  role = VALUES(role),
  password_plain = 'abcd',
  password_hash = NULL,
  active = 1;

CREATE TABLE IF NOT EXISTS app_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  sheet_name VARCHAR(120) NOT NULL,
  row_type VARCHAR(40) NOT NULL,
  row_sort INT NOT NULL DEFAULT 0,
  record_group_id VARCHAR(255) DEFAULT NULL,
  mrr_number VARCHAR(120) DEFAULT NULL,
  ge_no VARCHAR(120) DEFAULT NULL,
  invoice_no VARCHAR(190) DEFAULT NULL,
  supplier VARCHAR(255) DEFAULT NULL,
  truck_no VARCHAR(120) DEFAULT NULL,
  pending_stage VARCHAR(80) DEFAULT NULL,
  date_value VARCHAR(40) DEFAULT NULL,
  approval_status_plant VARCHAR(40) DEFAULT NULL,
  approval_status_accounts VARCHAR(40) DEFAULT NULL,
  approval_status_md VARCHAR(40) DEFAULT NULL,
  tally_posted TINYINT(1) NOT NULL DEFAULT 0,
  data_json LONGTEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_records_sheet (firm_id, sheet_name),
  KEY idx_records_mrr (firm_id, mrr_number),
  KEY idx_records_ge (firm_id, ge_no),
  KEY idx_records_pair (firm_id, ge_no, mrr_number),
  KEY idx_records_group (firm_id, record_group_id),
  KEY idx_records_lookup (firm_id, sheet_name, ge_no, mrr_number, row_type, row_sort),
  KEY idx_records_pending (firm_id, pending_stage),
  KEY idx_records_invoice (firm_id, invoice_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS approval_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  ge_no VARCHAR(120) DEFAULT NULL,
  mrr_number VARCHAR(120) NOT NULL,
  record_group_id VARCHAR(255) DEFAULT NULL,
  stage_name VARCHAR(80) NOT NULL,
  decision_value VARCHAR(40) NOT NULL,
  user_email VARCHAR(190) DEFAULT NULL,
  remark_text TEXT DEFAULT NULL,
  extra_json LONGTEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_approval_logs_mrr (firm_id, mrr_number, stage_name),
  KEY idx_approval_logs_pair (firm_id, ge_no, mrr_number, stage_name),
  KEY idx_approval_logs_group (firm_id, record_group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  supplier_name VARCHAR(255) NOT NULL,
  supplier_code VARCHAR(120) DEFAULT NULL,
  contact_person VARCHAR(190) DEFAULT NULL,
  phone_no VARCHAR(60) DEFAULT NULL,
  email VARCHAR(190) DEFAULT NULL,
  address_text TEXT DEFAULT NULL,
  district_name VARCHAR(120) DEFAULT NULL,
  gstin VARCHAR(60) DEFAULT NULL,
  state_name VARCHAR(120) DEFAULT NULL,
  state_code VARCHAR(10) DEFAULT NULL,
  pin_code VARCHAR(20) DEFAULT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_supplier_name (firm_id, supplier_name),
  KEY idx_suppliers_code (firm_id, supplier_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS state_master (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  state_name VARCHAR(120) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_state_name (state_name),
  KEY idx_state_active (active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO state_master (state_name, active) VALUES
  ('Andaman and Nicobar Islands', 1),
  ('Andhra Pradesh', 1),
  ('Arunachal Pradesh', 1),
  ('Assam', 1),
  ('Bihar', 1),
  ('Chandigarh', 1),
  ('Chhattisgarh', 1),
  ('Dadra and Nagar Haveli and Daman and Diu', 1),
  ('Delhi', 1),
  ('Goa', 1),
  ('Gujarat', 1),
  ('Haryana', 1),
  ('Himachal Pradesh', 1),
  ('Jammu and Kashmir', 1),
  ('Jharkhand', 1),
  ('Karnataka', 1),
  ('Kerala', 1),
  ('Ladakh', 1),
  ('Lakshadweep', 1),
  ('Madhya Pradesh', 1),
  ('Maharashtra', 1),
  ('Manipur', 1),
  ('Meghalaya', 1),
  ('Mizoram', 1),
  ('Nagaland', 1),
  ('Odisha', 1),
  ('Puducherry', 1),
  ('Punjab', 1),
  ('Rajasthan', 1),
  ('Sikkim', 1),
  ('Tamil Nadu', 1),
  ('Telangana', 1),
  ('Tripura', 1),
  ('Uttar Pradesh', 1),
  ('Uttarakhand', 1),
  ('West Bengal', 1)
ON DUPLICATE KEY UPDATE active = VALUES(active);

CREATE TABLE IF NOT EXISTS reel_po_rows (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  po_no VARCHAR(120) NOT NULL,
  po_date VARCHAR(40) DEFAULT NULL,
  supplier_name VARCHAR(255) DEFAULT NULL,
  po_details VARCHAR(255) DEFAULT NULL,
  erp_code VARCHAR(120) DEFAULT NULL,
  size_value VARCHAR(80) DEFAULT NULL,
  gsm_value VARCHAR(80) DEFAULT NULL,
  bf_value VARCHAR(80) DEFAULT NULL,
  reel_details VARCHAR(255) DEFAULT NULL,
  unit_value VARCHAR(30) DEFAULT NULL,
  po_rate DECIMAL(18,2) DEFAULT NULL,
  quantity_value DECIMAL(18,3) DEFAULT NULL,
  status_text VARCHAR(80) DEFAULT NULL,
  quantity_received DECIMAL(18,3) DEFAULT NULL,
  pending_quantity DECIMAL(18,3) DEFAULT NULL,
  closed_quantity DECIMAL(18,3) DEFAULT NULL,
  rapc_value DECIMAL(18,3) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_reel_po_no (firm_id, po_no),
  KEY idx_reel_po_supplier (firm_id, supplier_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS other_po_rows (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  po_no VARCHAR(120) NOT NULL,
  po_date VARCHAR(40) DEFAULT NULL,
  supplier_name VARCHAR(255) DEFAULT NULL,
  po_details VARCHAR(255) DEFAULT NULL,
  erp_code VARCHAR(120) DEFAULT NULL,
  size_value VARCHAR(80) DEFAULT NULL,
  gsm_value VARCHAR(80) DEFAULT NULL,
  bf_value VARCHAR(80) DEFAULT NULL,
  reel_details VARCHAR(255) DEFAULT NULL,
  unit_value VARCHAR(30) DEFAULT NULL,
  po_rate DECIMAL(18,2) DEFAULT NULL,
  quantity_value DECIMAL(18,3) DEFAULT NULL,
  status_text VARCHAR(80) DEFAULT NULL,
  quantity_received DECIMAL(18,3) DEFAULT NULL,
  pending_quantity DECIMAL(18,3) DEFAULT NULL,
  closed_quantity DECIMAL(18,3) DEFAULT NULL,
  rapc_value DECIMAL(18,3) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_other_po_no (firm_id, po_no),
  KEY idx_other_po_supplier (firm_id, supplier_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ge_entries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  ge_no VARCHAR(120) NOT NULL,
  mrr_no VARCHAR(120) DEFAULT NULL,
  entry_date VARCHAR(40) DEFAULT NULL,
  supplier_name VARCHAR(255) DEFAULT NULL,
  invoice_no VARCHAR(190) DEFAULT NULL,
  total_invoice_value DECIMAL(18,2) DEFAULT NULL,
  truck_no VARCHAR(120) DEFAULT NULL,
  pic1 LONGTEXT DEFAULT NULL,
  pic2 LONGTEXT DEFAULT NULL,
  pic3 LONGTEXT DEFAULT NULL,
  pic4 LONGTEXT DEFAULT NULL,
  pic5 LONGTEXT DEFAULT NULL,
  pic6 LONGTEXT DEFAULT NULL,
  pic7 LONGTEXT DEFAULT NULL,
  pic8 LONGTEXT DEFAULT NULL,
  mrr_complete TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_ge_no (firm_id, ge_no),
  KEY idx_ge_mrr (firm_id, mrr_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reel_mrr_parents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  record_group_id VARCHAR(255) NOT NULL,
  ge_no VARCHAR(120) NOT NULL,
  mrr_no VARCHAR(120) NOT NULL,
  mrr_form_id VARCHAR(120) DEFAULT NULL,
  entry_date VARCHAR(40) DEFAULT NULL,
  receipt_date VARCHAR(40) DEFAULT NULL,
  supplier_name VARCHAR(255) DEFAULT NULL,
  supplier_doc_no VARCHAR(190) DEFAULT NULL,
  truck_no VARCHAR(120) DEFAULT NULL,
  invoice_total_weight DECIMAL(18,3) DEFAULT NULL,
  actual_mrr_total_weight DECIMAL(18,3) DEFAULT NULL,
  required_reels DECIMAL(18,3) DEFAULT NULL,
  rows_added INT DEFAULT 0,
  mrr_type VARCHAR(80) DEFAULT NULL,
  invoice_basic_value DECIMAL(18,2) DEFAULT NULL,
  mrr_basic_value DECIMAL(18,2) DEFAULT NULL,
  e_way_bill_no VARCHAR(120) DEFAULT NULL,
  e_way_date VARCHAR(40) DEFAULT NULL,
  lr_no VARCHAR(120) DEFAULT NULL,
  insurance DECIMAL(18,2) DEFAULT NULL,
  round_off DECIMAL(18,2) DEFAULT NULL,
  plant_head_approval VARCHAR(40) DEFAULT NULL,
  accounts_approval VARCHAR(40) DEFAULT NULL,
  md_approval VARCHAR(40) DEFAULT NULL,
  pending_stage VARCHAR(80) DEFAULT NULL,
  tally_posted TINYINT(1) NOT NULL DEFAULT 0,
  extra_json LONGTEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_reel_mrr_parent (firm_id, ge_no, mrr_no),
  KEY idx_reel_mrr_parent_group (firm_id, record_group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reel_mrr_children (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  record_group_id VARCHAR(255) NOT NULL,
  ge_no VARCHAR(120) NOT NULL,
  mrr_no VARCHAR(120) NOT NULL,
  parent_id BIGINT UNSIGNED DEFAULT NULL,
  source_type VARCHAR(40) NOT NULL DEFAULT 'mrr_item',
  row_sort INT NOT NULL DEFAULT 0,
  s_no VARCHAR(40) DEFAULT NULL,
  description_text VARCHAR(255) DEFAULT NULL,
  hsn_code VARCHAR(60) DEFAULT NULL,
  sort_no VARCHAR(60) DEFAULT NULL,
  party_order_no VARCHAR(120) DEFAULT NULL,
  po_no VARCHAR(120) DEFAULT NULL,
  po_date VARCHAR(40) DEFAULT NULL,
  po_details VARCHAR(255) DEFAULT NULL,
  po_rate DECIMAL(18,2) DEFAULT NULL,
  gsm_value VARCHAR(80) DEFAULT NULL,
  size_value VARCHAR(80) DEFAULT NULL,
  unit_value VARCHAR(30) DEFAULT NULL,
  reels_value DECIMAL(18,3) DEFAULT NULL,
  weight_value DECIMAL(18,3) DEFAULT NULL,
  rate_value DECIMAL(18,2) DEFAULT NULL,
  amount_value DECIMAL(18,2) DEFAULT NULL,
  quantity_value DECIMAL(18,3) DEFAULT NULL,
  po_quantity DECIMAL(18,3) DEFAULT NULL,
  supplier_reel_no VARCHAR(120) DEFAULT NULL,
  our_reel_no VARCHAR(120) DEFAULT NULL,
  reel_details VARCHAR(255) DEFAULT NULL,
  erp_code VARCHAR(120) DEFAULT NULL,
  bf_value VARCHAR(80) DEFAULT NULL,
  extra_json LONGTEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_reel_mrr_child_pair (firm_id, ge_no, mrr_no),
  KEY idx_reel_mrr_child_parent (parent_id),
  KEY idx_reel_mrr_child_group (firm_id, record_group_id),
  KEY idx_reel_mrr_child_source (firm_id, ge_no, mrr_no, source_type, row_sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS other_mrr_parents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  record_group_id VARCHAR(255) NOT NULL,
  ge_no VARCHAR(120) NOT NULL,
  mrr_no VARCHAR(120) NOT NULL,
  mrr_form_id VARCHAR(120) DEFAULT NULL,
  entry_date VARCHAR(40) DEFAULT NULL,
  receipt_date VARCHAR(40) DEFAULT NULL,
  supplier_name VARCHAR(255) DEFAULT NULL,
  supplier_doc_no VARCHAR(190) DEFAULT NULL,
  truck_no VARCHAR(120) DEFAULT NULL,
  invoice_total_weight DECIMAL(18,3) DEFAULT NULL,
  actual_mrr_total_weight DECIMAL(18,3) DEFAULT NULL,
  rows_added INT DEFAULT 0,
  mrr_type VARCHAR(80) DEFAULT NULL,
  invoice_basic_value DECIMAL(18,2) DEFAULT NULL,
  mrr_basic_value DECIMAL(18,2) DEFAULT NULL,
  insurance DECIMAL(18,2) DEFAULT NULL,
  round_off DECIMAL(18,2) DEFAULT NULL,
  plant_head_approval VARCHAR(40) DEFAULT NULL,
  accounts_approval VARCHAR(40) DEFAULT NULL,
  md_approval VARCHAR(40) DEFAULT NULL,
  pending_stage VARCHAR(80) DEFAULT NULL,
  tally_posted TINYINT(1) NOT NULL DEFAULT 0,
  extra_json LONGTEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_other_mrr_parent (firm_id, ge_no, mrr_no),
  KEY idx_other_mrr_parent_group (firm_id, record_group_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS other_mrr_children (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  record_group_id VARCHAR(255) NOT NULL,
  ge_no VARCHAR(120) NOT NULL,
  mrr_no VARCHAR(120) NOT NULL,
  parent_id BIGINT UNSIGNED DEFAULT NULL,
  source_type VARCHAR(40) NOT NULL DEFAULT 'mrr_item',
  row_sort INT NOT NULL DEFAULT 0,
  s_no VARCHAR(40) DEFAULT NULL,
  description_text VARCHAR(255) DEFAULT NULL,
  hsn_code VARCHAR(60) DEFAULT NULL,
  sort_no VARCHAR(60) DEFAULT NULL,
  party_order_no VARCHAR(120) DEFAULT NULL,
  po_no VARCHAR(120) DEFAULT NULL,
  po_date VARCHAR(40) DEFAULT NULL,
  po_details VARCHAR(255) DEFAULT NULL,
  po_rate DECIMAL(18,2) DEFAULT NULL,
  gsm_value VARCHAR(80) DEFAULT NULL,
  size_value VARCHAR(80) DEFAULT NULL,
  unit_value VARCHAR(30) DEFAULT NULL,
  reels_value DECIMAL(18,3) DEFAULT NULL,
  weight_value DECIMAL(18,3) DEFAULT NULL,
  rate_value DECIMAL(18,2) DEFAULT NULL,
  amount_value DECIMAL(18,2) DEFAULT NULL,
  quantity_value DECIMAL(18,3) DEFAULT NULL,
  po_quantity DECIMAL(18,3) DEFAULT NULL,
  supplier_reel_no VARCHAR(120) DEFAULT NULL,
  our_reel_no VARCHAR(120) DEFAULT NULL,
  reel_details VARCHAR(255) DEFAULT NULL,
  erp_code VARCHAR(120) DEFAULT NULL,
  bf_value VARCHAR(80) DEFAULT NULL,
  extra_json LONGTEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_other_mrr_child_pair (firm_id, ge_no, mrr_no),
  KEY idx_other_mrr_child_parent (parent_id),
  KEY idx_other_mrr_child_group (firm_id, record_group_id),
  KEY idx_other_mrr_child_source (firm_id, ge_no, mrr_no, source_type, row_sort)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE reel_mrr_children
  ADD COLUMN IF NOT EXISTS source_type VARCHAR(40) NOT NULL DEFAULT 'mrr_item' AFTER parent_id;

ALTER TABLE other_mrr_children
  ADD COLUMN IF NOT EXISTS source_type VARCHAR(40) NOT NULL DEFAULT 'mrr_item' AFTER parent_id;

CREATE TABLE IF NOT EXISTS item_master (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  item_type VARCHAR(20) NOT NULL DEFAULT 'mrr',
  item_group_name VARCHAR(120) DEFAULT NULL,
  erp_code VARCHAR(120) DEFAULT NULL,
  item_name VARCHAR(255) NOT NULL,
  size_value VARCHAR(80) DEFAULT NULL,
  gsm_value VARCHAR(80) DEFAULT NULL,
  bf_value VARCHAR(80) DEFAULT NULL,
  unit_value VARCHAR(30) DEFAULT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_item_erp (firm_id, item_type, erp_code),
  UNIQUE KEY uniq_item_name (firm_id, item_type, item_name),
  KEY idx_item_active (firm_id, active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS purchase_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  pr_no VARCHAR(64) NOT NULL,
  department_name VARCHAR(120) DEFAULT NULL,
  requested_by VARCHAR(190) DEFAULT NULL,
  requisition_date VARCHAR(40) DEFAULT NULL,
  required_date VARCHAR(40) DEFAULT NULL,
  status_text VARCHAR(40) NOT NULL DEFAULT 'pending',
  remark_text TEXT DEFAULT NULL,
  created_by VARCHAR(190) DEFAULT NULL,
  approved_by VARCHAR(190) DEFAULT NULL,
  approved_at VARCHAR(40) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_pr_no (firm_id, pr_no),
  KEY idx_pr_status (firm_id, status_text)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS purchase_request_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  pr_id BIGINT UNSIGNED NOT NULL,
  item_id BIGINT UNSIGNED DEFAULT NULL,
  row_sort INT NOT NULL DEFAULT 0,
  erp_code VARCHAR(120) DEFAULT NULL,
  item_name VARCHAR(255) DEFAULT NULL,
  description_text VARCHAR(255) DEFAULT NULL,
  unit_value VARCHAR(30) DEFAULT NULL,
  qty_value DECIMAL(18,3) DEFAULT NULL,
  rate_value DECIMAL(18,2) DEFAULT NULL,
  amount_value DECIMAL(18,2) DEFAULT NULL,
  remark_text VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pr_items (firm_id, pr_id, row_sort),
  KEY idx_pr_items_item (firm_id, item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS item_groups (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  group_name VARCHAR(120) NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_group_name (group_name),
  KEY idx_group_active (active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO item_groups (group_name, active) VALUES
  ('Reel', 1),
  ('Other', 1)
ON DUPLICATE KEY UPDATE active = VALUES(active);

CREATE TABLE IF NOT EXISTS purchase_orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  po_no VARCHAR(64) NOT NULL,
  pr_id BIGINT UNSIGNED DEFAULT NULL,
  po_type VARCHAR(20) NOT NULL DEFAULT 'mrr',
  supplier_name VARCHAR(255) DEFAULT NULL,
  po_date VARCHAR(40) DEFAULT NULL,
  po_details TEXT DEFAULT NULL,
  status_text VARCHAR(40) NOT NULL DEFAULT 'draft',
  remark_text TEXT DEFAULT NULL,
  created_by VARCHAR(190) DEFAULT NULL,
  approved_by VARCHAR(190) DEFAULT NULL,
  approved_at VARCHAR(40) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_po_no (firm_id, po_no),
  KEY idx_po_status (firm_id, status_text),
  KEY idx_po_pr (firm_id, pr_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS purchase_order_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  po_id BIGINT UNSIGNED NOT NULL,
  pr_item_id BIGINT UNSIGNED DEFAULT NULL,
  item_id BIGINT UNSIGNED DEFAULT NULL,
  row_sort INT NOT NULL DEFAULT 0,
  supplier_name VARCHAR(255) DEFAULT NULL,
  erp_code VARCHAR(120) DEFAULT NULL,
  item_name VARCHAR(255) DEFAULT NULL,
  description_text VARCHAR(255) DEFAULT NULL,
  unit_value VARCHAR(30) DEFAULT NULL,
  qty_value DECIMAL(18,3) DEFAULT NULL,
  rate_value DECIMAL(18,2) DEFAULT NULL,
  amount_value DECIMAL(18,2) DEFAULT NULL,
  remark_text VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_po_items (firm_id, po_id, row_sort),
  KEY idx_po_items_pr_item (firm_id, pr_item_id),
  KEY idx_po_items_item (firm_id, item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Migration helpers (safe to run multiple times on MariaDB/MySQL variants that support IF NOT EXISTS).
ALTER TABLE purchase_request_items
  ADD COLUMN IF NOT EXISTS item_id BIGINT UNSIGNED DEFAULT NULL AFTER pr_id;

ALTER TABLE purchase_order_items
  ADD COLUMN IF NOT EXISTS pr_item_id BIGINT UNSIGNED DEFAULT NULL AFTER po_id,
  ADD COLUMN IF NOT EXISTS item_id BIGINT UNSIGNED DEFAULT NULL AFTER pr_item_id;

CREATE TABLE IF NOT EXISTS app_sequences (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  seq_name VARCHAR(120) NOT NULL,
  last_value INT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_firm_seq (firm_id, seq_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Reel-wise stock helpers (derived from reel_mrr_children + these tables)
CREATE TABLE IF NOT EXISTS reel_issue_entries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  job_no VARCHAR(120) NOT NULL,
  our_reel_no VARCHAR(120) NOT NULL,
  issue_weight DECIMAL(18,3) NOT NULL DEFAULT 0,
  issue_date VARCHAR(40) DEFAULT NULL,
  corrugation VARCHAR(120) DEFAULT NULL,
  erp_code VARCHAR(120) DEFAULT NULL,
  supplier_name VARCHAR(255) DEFAULT NULL,
  size_value VARCHAR(80) DEFAULT NULL,
  gsm_value VARCHAR(80) DEFAULT NULL,
  bf_value VARCHAR(80) DEFAULT NULL,
  rate_value DECIMAL(18,2) DEFAULT NULL,
  created_by VARCHAR(190) DEFAULT NULL,
  extra_json LONGTEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_reel_issue_reel (firm_id, our_reel_no),
  KEY idx_reel_issue_job (firm_id, job_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reel_return_entries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  job_no VARCHAR(120) NOT NULL,
  our_reel_no VARCHAR(120) NOT NULL,
  return_weight DECIMAL(18,3) NOT NULL DEFAULT 0,
  return_date VARCHAR(40) DEFAULT NULL,
  corrugation VARCHAR(120) DEFAULT NULL,
  erp_code VARCHAR(120) DEFAULT NULL,
  supplier_name VARCHAR(255) DEFAULT NULL,
  size_value VARCHAR(80) DEFAULT NULL,
  gsm_value VARCHAR(80) DEFAULT NULL,
  bf_value VARCHAR(80) DEFAULT NULL,
  rate_value DECIMAL(18,2) DEFAULT NULL,
  created_by VARCHAR(190) DEFAULT NULL,
  extra_json LONGTEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_reel_return_reel (firm_id, our_reel_no),
  KEY idx_reel_return_job (firm_id, job_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sales_orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  order_id VARCHAR(64) NOT NULL,
  order_date VARCHAR(40) DEFAULT NULL,
  company_name VARCHAR(255) DEFAULT NULL,
  po_number VARCHAR(120) DEFAULT NULL,
  erp_code VARCHAR(120) DEFAULT NULL,
  item_name VARCHAR(255) DEFAULT NULL,
  qty DECIMAL(18,3) DEFAULT NULL,
  rate DECIMAL(18,2) DEFAULT NULL,
  
  scheduled_date_1 VARCHAR(40) DEFAULT NULL,
  qty_1 DECIMAL(18,3) DEFAULT NULL,
  scheduled_date_2 VARCHAR(40) DEFAULT NULL,
  qty_2 DECIMAL(18,3) DEFAULT NULL,
  scheduled_date_3 VARCHAR(40) DEFAULT NULL,
  qty_3 DECIMAL(18,3) DEFAULT NULL,
  scheduled_date_4 VARCHAR(40) DEFAULT NULL,
  qty_4 DECIMAL(18,3) DEFAULT NULL,
  scheduled_date_5 VARCHAR(40) DEFAULT NULL,
  qty_5 DECIMAL(18,3) DEFAULT NULL,
  scheduled_date_6 VARCHAR(40) DEFAULT NULL,
  qty_6 DECIMAL(18,3) DEFAULT NULL,
  scheduled_date_7 VARCHAR(40) DEFAULT NULL,
  qty_7 DECIMAL(18,3) DEFAULT NULL,
  scheduled_date_8 VARCHAR(40) DEFAULT NULL,
  qty_8 DECIMAL(18,3) DEFAULT NULL,
  scheduled_date_9 VARCHAR(40) DEFAULT NULL,
  qty_9 DECIMAL(18,3) DEFAULT NULL,
  scheduled_date_10 VARCHAR(40) DEFAULT NULL,
  qty_10 DECIMAL(18,3) DEFAULT NULL,
  
  order_by VARCHAR(190) DEFAULT NULL,
  order_timestamp VARCHAR(40) DEFAULT NULL,
  email_id VARCHAR(190) DEFAULT NULL,
  po_type VARCHAR(40) DEFAULT NULL,
  salesman_email VARCHAR(190) DEFAULT NULL,
  sales_person VARCHAR(190) DEFAULT NULL,
  remarks TEXT DEFAULT NULL,
  
  last_billing_rate_1 DECIMAL(18,2) DEFAULT NULL,
  last_billing_date_1 VARCHAR(40) DEFAULT NULL,
  last_billing_rate_2 DECIMAL(18,2) DEFAULT NULL,
  last_billing_date_2 VARCHAR(40) DEFAULT NULL,
  last_rapc_1 DECIMAL(18,3) DEFAULT NULL,
  last_rapc_2 DECIMAL(18,3) DEFAULT NULL,
  
  approved_timestamp VARCHAR(40) DEFAULT NULL,
  approved_email VARCHAR(190) DEFAULT NULL,
  
  total_pending_qty DECIMAL(18,3) DEFAULT NULL,
  total_pending_order_value DECIMAL(18,2) DEFAULT NULL,
  punch_date VARCHAR(40) DEFAULT NULL,
  
  status_text VARCHAR(40) NOT NULL DEFAULT 'pending_approval', -- pending_approval, pending_scheduling, pending_jobs, approved, cancelled
  
  cancel_timestamp VARCHAR(40) DEFAULT NULL,
  cancel_by VARCHAR(190) DEFAULT NULL,
  cancel_reason TEXT DEFAULT NULL,
  cancel_qty DECIMAL(18,3) DEFAULT NULL,
  cancel_qty_reason TEXT DEFAULT NULL,
  cancel_qty_timestamp VARCHAR(40) DEFAULT NULL,
  cancel_qty_username_email VARCHAR(190) DEFAULT NULL,
  
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_sales_order_id (firm_id, order_id),
  KEY idx_sales_order_status (firm_id, status_text),
  KEY idx_sales_order_company (firm_id, company_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS companies (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  firm_id VARCHAR(64) NOT NULL,
  company_name VARCHAR(255) NOT NULL,
  address_text TEXT DEFAULT NULL,
  district_name VARCHAR(120) DEFAULT NULL,
  state_name VARCHAR(120) DEFAULT NULL,
  gst_no VARCHAR(60) DEFAULT NULL,
  email VARCHAR(190) DEFAULT NULL,
  contact_person VARCHAR(190) DEFAULT NULL,
  contact_number VARCHAR(60) DEFAULT NULL,
  pin_code VARCHAR(20) DEFAULT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_company_name (firm_id, company_name),
  KEY idx_companies_gst (firm_id, gst_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

